import type { Product } from '../models/productModel'

const getProducts = (): Product[] => {
	const products: Product[] = [
		{
			urlImgMain: '/productImages/main.jpg',
			urlImgSecond: '/productImages/secondaryMain.jpg',
			title: 'Tribeca Apartment',
			by: 'by Rob Johansen',
			date: 'AUG 21, 2023',
			tag: 'INTERIORS',
			key: '0',
		},
		{
			urlImgMain: '/productImages/1-main.jpg',
			urlImgSecond: '/productImages/1-secondary.jpg',
			title: 'Abe House',
			by: 'by masafumiharihaiarchitecture',
			date: 'AUG 21, 2023',
			tag: 'ARCHITECTURE',
			key: '1',
		},
		{
			urlImgMain: '/productImages/2-main.jpg',
			urlImgSecond: '/productImages/2-secondary.jpg',
			title: 'Neute Flagship',
			by: 'by Studio EEUW Archiv',
			date: 'AUG 20, 2023',
			tag: 'INTERIORS',
			key: '2',
		},
		{
			urlImgMain: '/productImages/3-main.jpg',
			urlImgSecond: '/productImages/3-secondary.jpg',
			title: 'Warm Ash Residence',
			by: 'by YWS STUDIO',
			date: 'AUG 19, 2023',
			tag: 'INTERIORS',
			key: '3',
		},
		{
			urlImgMain: '/productImages/4-main.jpg',
			urlImgSecond: '/productImages/4-secondary.jpg',
			title: 'ONE',
			by: 'by ambientdesigne',
			date: 'AUG 18, 2023',
			tag: 'ARCHITECTURE',
			key: '4',
		},
		{
			urlImgMain: '/productImages/5-main.jpg',
			urlImgSecond: '/productImages/5-secondary.jpg',
			title: 'De Vimy Residence',
			by: 'by Vives St-Laurent',
			date: 'AUG 18, 2023',
			tag: 'INTERIORS',
			key: '5',
		},
		{
			urlImgMain: '/productImages/6-main.jpg',
			urlImgSecond: '/productImages/6-secondary.jpg',
			title: 'Alabaster Side Table',
			by: 'by MOCK STUDIO',
			date: 'AUG 17, 2023',
			tag: 'FURTINURE',
			key: '6',
		},
		{
			urlImgMain: '/productImages/7-main.jpg',
			urlImgSecond: '/productImages/7-secondary.jpg',
			title: 'Holte Residence',
			by: 'by Reform',
			date: 'AUG 17, 2023',
			tag: 'INTERIORS',
			key: '7',
		},
		{
			urlImgMain: '/productImages/8-main.jpg',
			urlImgSecond: '/productImages/8-secondary.jpg',
			title: 'Pujades',
			by: 'by Antoni Pallejà Office',
			date: 'AUG 16, 2023',
			tag: 'INTERIORS',
			key: '8',
		},
		{
			urlImgMain: '/productImages/9-main.jpg',
			urlImgSecond: '/productImages/9-secondary.jpg',
			title: 'Martelaar',
			by: 'by Machteld DHollander',
			date: 'AUG 16, 2023',
			tag: 'ARCHITECTURE',
			key: '9',
		},
		{
			urlImgMain: '/productImages/10-main.jpg',
			urlImgSecond: '/productImages/10-secondary.jpg',
			title: 'Dune Coffee Table',
			by: 'by Pietro Franceschini',
			date: 'AUG 15, 2023',
			tag: 'FURNITURE',
			key: '10',
		},
		{
			urlImgMain: '/productImages/11-main.jpg',
			urlImgSecond: '/productImages/11-secondary.jpg',
			title: 'Tellus',
			by: 'by Emma Olbers',
			date: 'AUG 15, 2023',
			tag: 'FURNITURE',
			key: '11',
		},
		{
			urlImgMain: '/productImages/n-main.jpg',
			urlImgSecond: '/productImages/n-secondary.jpg',
			title: 'Tellus',
			by: 'by Emma Olbers',
			date: 'AUG 15, 2023',
			tag: 'FURNITURE',
			key: '12',
		},
		{
			urlImgMain: '/productImages/12-main.webp',
			urlImgSecond: '/productImages/12-secondary.webp',
			title: 'PK24 - Wicker',
			by: '$21170 USD',
			date: 'FRITZ HANSEN',
			tag: 'LOUNGE CHAIRS',
			key: '13',
		},
		{
			urlImgMain: '/productImages/13-main.jpg',
			urlImgSecond: '/productImages/13-secondary.jpg',
			title: 'Herne Hill',
			by: 'by TYPE',
			date: 'AUG 14, 2023',
			tag: 'ARCHITECTURE',
			key: '14',
		},
		{
			urlImgMain: '/productImages/14-main.webp',
			urlImgSecond: '/productImages/14-secondary.webp',
			title: 'Clerici Lounge Two-Seat',
			by: '$2139 USD',
			date: 'MATTIAZZI',
			tag: 'SOFAS',
			key: '15',
		},
		{
			urlImgMain: '/productImages/15-main.webp',
			urlImgSecond: '/productImages/15-secondary.webp',
			title: 'Clay House',
			by: 'by Bureau de Change',
			date: 'AUG 14, 2023',
			tag: 'INTERIORS',
			key: '16',
		},
		{
			urlImgMain: '/productImages/16-main.webp',
			urlImgSecond: '/productImages/16-secondary.webp',
			title: 'MG501 Cuba Chair',
			by: '$1180 USD',
			date: 'CARL HANSEN & SON',
			tag: 'LOUNGE CHAIRS',
			key: '17',
		},
	]
	return products
}

export default getProducts
